{
  "type": "record",
  "name": "Command",
  "namespace": "com.iot.commands",
  "fields": [
    {
      "name": "commandId",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "deviceId",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "userId",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "deviceType",
      "type": {
        "type": "enum",
        "name": "DeviceType",
        "symbols": [
          "UNKNOWN",
          "SMART_LIGHT",
          "SMART_PLUG",
          "THERMOSTAT"
        ]
      },
      "default": "UNKNOWN"
    },
    {
      "name": "payload",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "createdAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}